-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  account_type character varying NOT NULL,
  parent_id uuid,
  is_transactional boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exp_date date NOT NULL DEFAULT CURRENT_DATE,
  sub_contractor text,
  payee_id uuid,
  creditor_account text,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  vat_amount numeric DEFAULT 0 CHECK (vat_amount >= 0::numeric),
  discount_amount numeric DEFAULT 0,
  discount_account character varying,
  paid_amount numeric NOT NULL DEFAULT 0,
  payment_method text DEFAULT 'كاش'::text CHECK (payment_method = ANY (ARRAY['كاش'::text, 'تحويل بنكي'::text, 'شيك'::text, 'عُهدة'::text, 'آجل'::text, 'تسوية داخلية'::text])),
  payment_account text DEFAULT '125 - عُهد الموظفين والمواقع'::text,
  notes text,
  is_posted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  site_ref text,
  payee_name text,
  employee_name character varying,
  invoice_image text,
  lines_data jsonb DEFAULT '[]'::jsonb,
  is_deducted_in_claim boolean DEFAULT false,
  claim_id uuid,
  is_auto_distributed boolean DEFAULT false,
  total_price numeric DEFAULT 0,
  main_category text,
  is_deleted boolean DEFAULT false,
  job_order_id uuid,
  is_deducted_from_contractor boolean DEFAULT false,
  created_by uuid,
  expense_number text,
  fleet_operation_id uuid,
  shift_id uuid,
  CONSTRAINT expenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number text NOT NULL UNIQUE,
  boq_budget_id uuid,
  assigned_qty numeric DEFAULT 0,
  unit_price numeric DEFAULT 0,
  status text DEFAULT 'جاري التنفيذ'::text CHECK (status = ANY (ARRAY['مسودة'::text, 'جاري التنفيذ'::text, 'مكتمل'::text, 'موقوف'::text, 'جاري التسليم'::text, 'مفوتر'::text, 'تم التحصيل'::text])),
  start_date date DEFAULT CURRENT_DATE,
  end_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  executor_type text DEFAULT 'تنفيذ ذاتي'::text,
  contractor_id uuid,
  customer_id uuid,
  CONSTRAINT job_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.labor_daily_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_date date NOT NULL,
  worker_name text NOT NULL,
  site_ref text,
  work_item text,
  unit text,
  skill_level text,
  daily_wage numeric DEFAULT 0,
  attendance_value numeric DEFAULT 0,
  sub_contractor text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  worker_partner_id uuid,
  sub_contractor_id uuid,
  is_posted boolean DEFAULT false,
  work_item_id uuid,
  tareeha numeric,
  productivity numeric,
  completion_percentage numeric,
  credit_account_id uuid DEFAULT '39f878cd-dc58-4a2a-a199-50f6fca983d4'::uuid,
  debit_account_id uuid DEFAULT '70d181ba-6385-4c1e-b0fc-d5b1f800dd2c'::uuid,
  production_desc text,
  completed_quantity numeric DEFAULT 0,
  number_of_workers integer DEFAULT 1,
  job_order_id uuid,
  CONSTRAINT labor_daily_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.journal_headers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_date date NOT NULL,
  description character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'draft'::character varying,
  reference_id uuid,
  v_type text,
  fleet_operation_id uuid,
  CONSTRAINT journal_headers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.journal_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  header_id uuid NOT NULL,
  account_id uuid NOT NULL,
  partner_id uuid,
  item_name character varying,
  quantity numeric DEFAULT 1,
  unit_price numeric DEFAULT 0,
  debit numeric NOT NULL DEFAULT 0,
  credit numeric NOT NULL DEFAULT 0,
  notes text,
  tax_amount numeric DEFAULT 0,
  tax_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  delegate_id uuid,
  fleet_operation_id uuid,
  CONSTRAINT journal_lines_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  partner_type character varying NOT NULL,
  identity_number character varying,
  identity_expiry_date date,
  identity_image_url text,
  phone character varying,
  address text,
  vat_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  job_role character varying,
  account_id uuid,
  is_active boolean DEFAULT true,
  credit_limit numeric DEFAULT 0,
  credit_days integer DEFAULT 0,
  bottle_custody numeric DEFAULT 0,
  location_lat numeric,
  location_lng numeric,
  route_name text,
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid,
  action text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cash_flows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  flow_type character varying NOT NULL CHECK (flow_type::text = ANY (ARRAY['inflow'::character varying::text, 'outflow'::character varying::text])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  category character varying NOT NULL,
  sub_category text,
  payment_method character varying DEFAULT 'نقدي'::character varying,
  reference_number character varying,
  description text,
  account_id uuid,
  partner_id uuid,
  is_reconciled boolean DEFAULT false,
  reconciled_date date,
  created_by uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  source_id uuid,
  source_type character varying,
  CONSTRAINT cash_flows_pkey PRIMARY KEY (id)
);
CREATE TABLE public.financial_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_year integer NOT NULL,
  plan_month integer NOT NULL,
  category text NOT NULL,
  item_name text NOT NULL,
  planned_amount numeric DEFAULT 0,
  actual_amount numeric DEFAULT 0,
  notes text,
  CONSTRAINT financial_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number character varying NOT NULL UNIQUE,
  date date NOT NULL DEFAULT CURRENT_DATE,
  partner_id uuid,
  client_name character varying,
  description text,
  materials_discount numeric DEFAULT 0,
  taxable_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  guarantee_percent numeric DEFAULT 0,
  guarantee_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  debit_account_id uuid DEFAULT '4f828d0d-a1f4-4762-83e3-c17dafae802d'::uuid,
  credit_account_id uuid DEFAULT '6667f91a-9478-49ab-9721-521ee09381fa'::uuid,
  materials_acc_id uuid DEFAULT '4f828d0d-a1f4-4762-83e3-c17dafae802d'::uuid,
  guarantee_acc_id uuid DEFAULT '4f828d0d-a1f4-4762-83e3-c17dafae802d'::uuid,
  tax_acc_id uuid DEFAULT '6667f91a-9478-49ab-9721-521ee09381fa'::uuid,
  skip_zatca boolean DEFAULT false,
  status character varying DEFAULT 'معلق'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  due_in_days integer DEFAULT 0,
  due_date date,
  paid_amount numeric DEFAULT 0,
  lines_data jsonb DEFAULT '[]'::jsonb,
  fleet_operation_id uuid,
  job_order_id uuid,
  warehouse_id uuid,
  delegate_id uuid,
  payment_method character varying DEFAULT 'آجل'::character varying,
  shift_id uuid,
  created_by uuid,
  payment_status text DEFAULT 'unpaid'::text,
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.journal_errors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  error_type text,
  description text,
  is_fixed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT journal_errors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  type text,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  title text NOT NULL DEFAULT 'إشعار جديد'::text,
  content text NOT NULL DEFAULT 'يوجد تحديث جديد'::text,
  related_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voucher_number text NOT NULL UNIQUE,
  date date NOT NULL DEFAULT CURRENT_DATE,
  amount numeric NOT NULL DEFAULT 0 CHECK (amount > 0::numeric),
  partner_id uuid,
  credit_account_id uuid,
  payment_method text,
  reference_no text,
  description text,
  notes text,
  status text NOT NULL DEFAULT 'مسودة'::text,
  is_posted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  debit_account_id uuid,
  site_ref text,
  related_expense_id uuid,
  sub_claim_id uuid,
  fleet_operation_id uuid,
  shift_id uuid,
  CONSTRAINT payment_vouchers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payroll_slips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  emp_id uuid,
  month text NOT NULL,
  basic_salary numeric DEFAULT 0,
  total_advances numeric DEFAULT 0,
  total_deductions numeric DEFAULT 0,
  net_salary numeric NOT NULL,
  is_posted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  amount_to_pay numeric DEFAULT 0,
  allowances numeric DEFAULT 0,
  status text DEFAULT 'غير مدفوع'::text,
  CONSTRAINT payroll_slips_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text UNIQUE,
  role text DEFAULT 'staff'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'manager'::text, 'staff'::text, 'contractor'::text, 'client'::text])),
  permissions jsonb DEFAULT '{}'::jsonb,
  signature_url text,
  linked_partner_id uuid,
  avatar_url text,
  nickname text,
  phone_number text,
  full_name text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  is_admin boolean DEFAULT false,
  is_active boolean DEFAULT true,
  quick_links jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.receipt_vouchers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL DEFAULT CURRENT_DATE,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_method text NOT NULL,
  notes text,
  partner_id uuid,
  invoice_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  receipt_number character varying UNIQUE,
  status character varying DEFAULT 'مسودة'::character varying,
  safe_bank_acc_id uuid,
  partner_acc_id uuid,
  reference_number text,
  attachment_url text,
  job_order_id uuid,
  delegate_id uuid,
  shift_id uuid,
  fleet_operation_id uuid,
  CONSTRAINT receipt_vouchers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sys_financial_reports (
  report_name character varying NOT NULL,
  report_data jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sys_financial_reports_pkey PRIMARY KEY (report_name)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL,
  theme_config jsonb DEFAULT '{"brand_gold": "#C5A059", "glass_blur": "15px", "bg_gradient": "linear-gradient(180deg, #43342E 0%, #8C6A5D 100%)", "glass_opacity": 0.7}'::jsonb,
  privacy_settings jsonb DEFAULT '{"show_activity_log": true, "show_online_status": true}'::jsonb,
  notifications jsonb DEFAULT '{"email_alerts": true, "push_notifications": false}'::jsonb,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  type text NOT NULL,
  category text,
  subject text NOT NULL,
  details text,
  status text DEFAULT 'pending'::text,
  admin_note text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  description text,
  status text DEFAULT 'pending'::text,
  priority text DEFAULT 'normal'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_tasks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.violations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date DEFAULT CURRENT_DATE,
  partner_id uuid,
  emp_name text,
  profession text,
  site_name text,
  reason text,
  amount numeric,
  image_url text,
  is_posted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  debit_account_id uuid,
  credit_account_id uuid,
  violation_type text DEFAULT 'غرامة'::text,
  boq_item_id uuid,
  is_deleted boolean DEFAULT false,
  CONSTRAINT violations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  unit character varying NOT NULL DEFAULT 'حبة'::character varying,
  current_quantity numeric DEFAULT 0,
  reorder_level numeric DEFAULT 5,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  code character varying,
  default_price numeric DEFAULT 0,
  suggested_price numeric DEFAULT 0,
  cost_price numeric DEFAULT 0,
  barcode character varying,
  is_active boolean DEFAULT true,
  item_type text DEFAULT 'water_product'::text,
  is_returnable_bottle boolean DEFAULT false,
  tax_rate numeric DEFAULT 15,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_number character varying NOT NULL UNIQUE,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['in'::text, 'out'::text, 'transfer_out'::text, 'transfer_in'::text, 'sales_deduction'::text, 'waste'::text, 'empty_return'::text])),
  quantity numeric NOT NULL,
  item_id uuid,
  partner_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  unit_price numeric DEFAULT 0,
  notes text,
  status character varying DEFAULT 'pending'::character varying,
  total_price numeric DEFAULT 0,
  journal_id uuid,
  fleet_operation_id uuid,
  invoice_id uuid,
  warehouse_id uuid,
  delegate_id uuid,
  tax_amount numeric DEFAULT 0,
  include_tax boolean DEFAULT false,
  destination_warehouse_id uuid,
  shift_id uuid,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.manual_journals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  voucher_number text,
  entry_date date NOT NULL,
  description text,
  debit_account_id uuid,
  credit_account_id uuid,
  partner_id uuid,
  project_id uuid,
  job_order_id uuid,
  amount numeric NOT NULL,
  status text DEFAULT 'مسودة'::text,
  is_posted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT manual_journals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fleet_vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plate_number text NOT NULL,
  vehicle_model text,
  driver_id uuid,
  status text DEFAULT 'متاح'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fleet_vehicles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fleet_operations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  operation_number text NOT NULL UNIQUE,
  operation_date date NOT NULL DEFAULT CURRENT_DATE,
  vehicle_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  status text DEFAULT 'مفتوح'::text,
  total_sales numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  inventory_cost numeric DEFAULT 0,
  net_profit numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  total_cost numeric DEFAULT 0,
  warehouse_id uuid,
  description text,
  start_km numeric DEFAULT 0,
  end_km numeric DEFAULT 0,
  CONSTRAINT fleet_operations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type character varying DEFAULT 'main'::character varying CHECK (type::text = ANY (ARRAY['main'::character varying, 'sub'::character varying, 'vehicle'::character varying, 'pos'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  delegate_id uuid,
  location text,
  phone text,
  manager_name text,
  description text,
  vehicle_id uuid,
  cash_account_id uuid,
  CONSTRAINT warehouses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.warehouse_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid NOT NULL,
  item_id uuid NOT NULL,
  quantity numeric DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT warehouse_inventory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehicle_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fleet_operation_id uuid,
  item_id uuid,
  quantity numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  loaded_qty numeric DEFAULT 0,
  sold_qty numeric DEFAULT 0,
  returned_qty numeric DEFAULT 0,
  waste_qty numeric DEFAULT 0,
  shortage_qty numeric DEFAULT 0,
  CONSTRAINT vehicle_inventory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pos_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  delegate_id uuid,
  warehouse_id uuid,
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  starting_cash numeric NOT NULL DEFAULT 0,
  expected_cash numeric DEFAULT 0,
  actual_cash numeric DEFAULT 0,
  total_sales numeric DEFAULT 0,
  total_cash_sales numeric DEFAULT 0,
  total_card_sales numeric DEFAULT 0,
  total_credit_sales numeric DEFAULT 0,
  shortage_overage numeric DEFAULT 0,
  status character varying NOT NULL DEFAULT 'open'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  bottles_sold numeric DEFAULT 0,
  bottles_returned numeric DEFAULT 0,
  bottles_shortage numeric DEFAULT 0,
  starting_bottles numeric DEFAULT 0,
  expected_bottles numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  fleet_operation_id uuid,
  closing_notes text,
  actual_bottles numeric DEFAULT 0,
  CONSTRAINT pos_shifts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_operations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  operation_date date NOT NULL DEFAULT CURRENT_DATE,
  operation_type text NOT NULL,
  description text NOT NULL,
  client_id uuid,
  employee_id uuid,
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  commission_percentage numeric NOT NULL DEFAULT 0 CHECK (commission_percentage >= 0::numeric AND commission_percentage <= 100::numeric),
  commission_amount numeric NOT NULL DEFAULT 0,
  net_profit numeric NOT NULL DEFAULT 0,
  debit_account_id uuid,
  revenue_account_id uuid,
  commission_expense_account_id uuid,
  journal_id uuid,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['draft'::text, 'completed'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT service_operations_pkey PRIMARY KEY (id)
);
